### ISSUE TITLE
Getting List of actors and director for a movie possible?

### ISSUE THREAD

**Issue by benpla** [Gubchik123/obsidian-movie-search-plugin#1]
First: I love your plugin!
I finally have a way to track the movies I've watched all over the Internet in one place without much effort.
The cherry on the cake for me would be to be able to include a list of actors in the template, as I like to watch the movies along actors and directors.

**Comment by Gubchik123** [comment]
Thank you so much for your feedback and kind words! I'm thrilled to hear that you're finding the "Movie Search" plugin useful for tracking your watched movies.

Regarding your suggestion about including a list of actors in the template, I really appreciate the idea. As a Python Developer, my expertise lies more in Python rather than TypeScript, the programming language used in the plugin. However, I find your suggestion incredibly useful and something that would enhance the plugin's functionality for many users, including myself.

I'll definitely take a closer look at it over the weekend, and see how feasible it is to implement. 

In the meantime, feel free to share the "Movie Search" plugin with your friends and let them know about it. Again, thank you for your input, and I'm glad to have you as a user of the "Movie Search" plugin!

**Comment by Gubchik123** [comment]
I've set aside some time until the weekend to delve into your idea of including a director and a list of actors in the template. After exploring the feasibility, I've added more template variables, including: `main_actors` and `director`, to enhance the plugin's capabilities.

Feel free to update the plugin to access these new features. Thank you once again for your valuable input, and I hope you continue to find the "Movie Search" plugin useful!

**Comment by benpla** [comment]
I have updated the plugin and what can I say: it works!
Thank you very much!

**Comment by Gubchik123** [comment]
Your gratitude is heartwarming! If you appreciate the plugin and find it helpful, I'd be grateful for your support: [BuyMeACoffee](https://www.buymeacoffee.com/gubchik123). 

Your generosity fuels my motivation to continue refining and enhancing the plugin after work. Thank you for considering! ☕️😄
